### ISSUE TITLE
Collection.AddWrap must return id

### ISSUE THREAD

**Issue by wraptrack** [UlrichFreiberg/WrapTrack.Stf#13]
We need 'Collection.AddWrap' to return the id (intern id or tracking id) of the new wrap.

Tc013 needs this information (tc013 not completed) and some other test cases need it too because function Collection.GetRandomWrap is not usefull in all situation after new business rules are added to the site.

**Comment by brobinsondk** [comment]
Done and checked in. Commit d796f056. 30th April 2018
