### ISSUE TITLE
Scription of test cases related to 'Upload model images'

### ISSUE THREAD

**Issue by wraptrack** [UlrichFreiberg/WrapTrack.Stf#15]
Tc020

**Comment by brobinsondk** [comment]
I'll take this one

**Comment by wraptrack** [comment]
Der bliver ikke klikket på knap, som fører til upload siden. Når man debugger ser det ud til at knappen bliver identificeret og anset som enablet men ikke visible. 

Jeg ved ikke, hvordan man kommer videre. Har uden held forsøgt forskelligt fra wt siden.

**Comment by wraptrack** [comment]
Solved by Ulrich (issue #24)
