### ISSUE TITLE
Reserving TestCase040 for Scripting for Warp Visit

### ISSUE THREAD

**Issue by brobinsondk** [UlrichFreiberg/WrapTrack.Stf#17]
Explanation: 
Some wrap owners lend their wraps to other people. Maybe the borrower considering to buy the wrap – or just want to try a special model  (there are more reasons). In more random cases the wrap is send from borrower to borrower in a chain.

Some borrowers  want to make a review of the wrap..

Wraptrack supports this behavior. We call it 'wrap visit' and distinguish between three kind:
Holiday wrap
Tester
Rent wrap

**Comment by wraptrack** [comment]
New name =  TC024

**Comment by brobinsondk** [comment]
Checked in. Closing Issue. Done
