### ISSUE TITLE
Type casting in WrapInfoMappe

### ISSUE THREAD

**Issue by wraptrack** [UlrichFreiberg/WrapTrack.Stf#3]
Problem arise from test case 008: I want to validate if number of private pictures is correct. But the variable is defined as string, so instead of adding 1 to 'before_ownership_pic' here is a string-concat in line 58 (StfAssert in line 59 fails). 

I could'ent get type casting to work in wtAPI.cs (func WrapInfoMapper). Will be nice if NumOfOwnershipPic was an integer like 'NumOf Pictures' in same func.

**Comment by UlrichFreiberg** [comment]
Resolved
