### ISSUE TITLE
Model reltated to test script 016 need update

### ISSUE THREAD

**Issue by wraptrack** [UlrichFreiberg/WrapTrack.Stf#30]
When adding a new model (http://wt.troldvaerk.org/Catalog/brand/289) you need to select a value in the pattern-select.

Our brand.AddModel accepts parameter pattern = null 
      -->  public bool AddModel(string modelName, string pattern = null)
In new version of wraptrack pattern = null means that you have to select '--- without pattern ---' in pattern select box.

**Comment by wraptrack** [comment]
The Pattern select box has id="sel_pattern"

**Comment by UlrichFreiberg** [comment]
Fixed pls verify

**Comment by wraptrack** [comment]
Verified
