### ISSUE TITLE
WrapTrackShell.signup does not set CurrentLoggedInUser. 

### ISSUE THREAD

**Issue by brobinsondk** [UlrichFreiberg/WrapTrack.Stf#33]
See TC 027.

  StfAssert.IsNotNull("wrapTrackShell", WrapTrackShell);
  WrapTrackShell.SignUp();

We do a signup and then do not do a login (the assumption is that after signup we are logged in as that user.... as on site)

In TC027 I would like to use the username to check whether news story created correctly, but I have no way to get the current logged in user details.

**Comment by UlrichFreiberg** [comment]
Resolved - pls verify

**Comment by wraptrack** [comment]
Verified and closed
