### ISSUE TITLE
Function RandomWrap - less random?

### ISSUE THREAD

**Issue by wraptrack** [UlrichFreiberg/WrapTrack.Stf#4]
Problem arise from test case 009: We do something to wrap A and then want to do something else to another wrap.

Function Collection.GetRandomWrap() is a nice function, but in this case we need to sure not to get wrap A again. 

So function GetRandomWrap has to be less random - or we need another function too. Maybe a (not mandatory) parameter (type IWrap) for GetRandomWrap meaning "I dont want this wrap" ?

**Comment by UlrichFreiberg** [comment]
Solved by Commit cc34a53c
